export const productdata = [
  {
    id: 1,
    name: "Calcium",
    imgSrc: "/health/calcium.jpg",
    category: "health",
    price: "500",
    brand: "HUM",
    quantity: 1,
  },
  {
    id: 2,
    name: "Vitamins",
    imgSrc: "/health/vitamins.jpg",
    category: "health",
    price: "450",
    brand: "HUM",
    quantity: 1,
  },
  {
    id: 3,
    name: "Serotonin",
    imgSrc: "/health/serotonin.jfif",
    category: "health",
    price: "550",
    brand: "Swanson",
    quantity: 1,
  },
  {
    id: 4,
    name: "daily Cleanse",
    imgSrc: "/health/daily_cleanse.jpg",
    category: "health",
    price: "500",
    brand: "Swanson",
    quantity: 1,
  },
  {
    id: 5,
    name: "Adreline",
    imgSrc: "/health/adreline.png",
    category: "health",
    price: "700",
    brand: "muscle_blaze",
    quantity: 1,
  },
  {
    id: 6,
    name: "Anti Ageing",
    imgSrc: "/health/antiAging.jfif",
    category: "health",
    price: "500",
    brand: "Swanson",
    quantity: 1,
  },
  {
    id: 7,
    name: "Biotin",
    imgSrc: "/health/biotin.jpg",
    category: "health",
    price: "400",
    brand: "HUM",
    quantity: 1,
  },
  {
    id: 8,
    name: "Fish Oil",
    imgSrc: "/health/fishOil.jpeg",
    category: "health",
    price: "650",
    brand: "muscle_blaze",
    quantity: 1,
  },
  {
    id: 9,
    name: "glutamine",
    imgSrc: "/health/glutamine.jpg",
    category: "health",
    price: "700",
    brand: "muscle_blaze",
    quantity: 1,
  },
  {
    id: 10,
    name: "Whey",
    imgSrc: "/health/whey.png",
    category: "health",
    price: "1400",
    brand: "muscle_blaze",
    quantity: 1,
  },
  {
    id: 11,
    name: "AcneTame",
    imgSrc: "/skin/acnetame.jpg",
    category: "skin",
    price: "1000",
    brand: "revlon",
    quantity: 1,
  },
  {
    id: 12,
    name: "CollaGen",
    imgSrc: "/skin/collagen.jpg",
    category: "skin",
    price: "800",
    brand: "revlon",
    quantity: 1,
  },
  {
    id: 13,
    name: "Epinonce",
    imgSrc: "/skin/epinonce.png",
    category: "skin",
    price: "1200",
    brand: "HUM",
    quantity: 1,
  },
  {
    id: 14,
    name: "Face Cream",
    imgSrc: "/skin/facecream.jpg",
    category: "skin",
    price: "350",
    brand: "Swanson",
    quantity: 1,
  },
  {
    id: 15,
    name: "Face Cream",
    imgSrc: "/skin/glow.png",
    category: "skin",
    price: "700",
    brand: "Swanson",
    quantity: 1,
  },
  {
    id: 16,
    name: "Honey Drop",
    imgSrc: "/skin/honeyDrop.png",
    category: "skin",
    price: "1250",
    brand: "revlon",
    quantity: 1,
  },
  {
    id: 17,
    name: "Face Mask",
    imgSrc: "/skin/mask.jpg",
    category: "skin",
    price: "550",
    brand: "HUM",
    quantity: 1,
  },
  {
    id: 18,
    name: "moisture Cream",
    imgSrc: "/skin/moistureCream.jfif",
    category: "skin",
    price: "550",
    brand: "revlon",
    quantity: 1,
  },
  {
    id: 19,
    name: "Sun Screen",
    imgSrc: "/skin/sunscreen.jfif",
    category: "skin",
    price: "250",
    brand: "muscle_blaze",
    quantity: 1,
  },
  {
    id: 20,
    name: "Shampoo",
    imgSrc: "/skin/shampoo.jfif",
    category: "skin",
    price: "350",
    brand: "muscle_blaze",
    quantity: 1,
  },
];
